server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: employee
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
        - id: department
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
